### ISSUE TITLE
Device_state_attribute no longer accepted

### ISSUE THREAD

**Issue by bwaayer** [muxa/home-assistant-niwa-tides#1]
Hey, 
Just setting up the integration, and I believe it needs updated to replace device_state_attribute as it's been phased out earlier last year?
Receiving the current error: 

`Entity sensor.local_tides (<class 'custom_components.niwa_tides.sensor.NiwaTidesInfoSensor'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by muxa** [comment]
Thanks @bwaayer for reporting this. This is a warning, so it will still work for the next few releases. I'll get this updated in the next few days

**Comment by muxa** [comment]
It turned out to be a very easy fix, so I just fixes this in https://github.com/muxa/home-assistant-niwa-tides/releases/tag/v1.1.2
HACS should pick this up within 24h.
