### ISSUE TITLE
Is this project no longer active?

### ISSUE THREAD

**Issue by deanfourie1** [muxa/home-assistant-niwa-tides#4]
Is this repo still maintained?

**Comment by shanekuz** [comment]
This seems to have stopped working, is anyone maintaining this?

**Comment by shanekuz** [comment]
I have done a little trial and error with the code here dean, i have found the api wants the lat as a number less than 29 so if you change your value you pass from 36 to -36 it all seems to work again.  This fixed home assistant integration anyway

**Comment by muxa** [comment]
It's still working for me. This project is provided as is with no support or guarantees. Pull requests are accepted, but with no guarantees for time when they will be reviewed or merged (I'm very busy lately and have no time to spend on this)

**Comment by craigstanton** [comment]
@shanekuz New Zealand is in the southern hemisphere, all latitudes should be between -29 to -53

**Comment by deanfourie1** [comment]
Great thanks,

Could you please give me an example of the syntax used to specify the API key and secret? Is this stored in the configuration.yaml or in secrets.yaml?

Thank you
