### ISSUE TITLE
Adding the API Key and Secret

### ISSUE THREAD

**Issue by deanfourie1** [muxa/home-assistant-niwa-tides#5]
Sorry, I would love some help on how to add the API key and the Secret Key?

I cant figure out where to add these and what syntax we use to add these as.

Thanks

**Comment by makerOfStuf** [comment]
Add the sensor configuration as described to the configuration.yaml file of your Home Assistant. You can install Visual Studio Code to edit. You only need the API key in the config.

**Comment by deanfourie1** [comment]
> Add the sensor configuration as described to the configuration.yaml file of your Home Assistant. You can install Visual Studio Code to edit. You only need the API key in the config.

Yes, thats the KEY

"you only need the API key in the config"

Thanks
