### ISSUE TITLE
Deprecated constant error

### ISSUE THREAD

**Issue by gromitn** [muxa/home-assistant-niwa-tides#6]
Hi
Getting an error:

`LENGTH_METERS was used from niwa_tides, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please create a bug report at https://github.com/muxa/home-assistant-niwa-tides/issues`

What to do please?

**Comment by Krispkiwi** [comment]
> Hi Getting an error:
> 
> `LENGTH_METERS was used from niwa_tides, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please create a bug report at https://github.com/muxa/home-assistant-niwa-tides/issues`
> 
> What to do please?

Wait for the author to update i guess

**Comment by muxa** [comment]
Fixed in v1.1.3
